[metadata.heroku]
  root-package = "github.com/seeeturtle/kbo"
  go-version = "1.8.3"
  install = [ "./..." ]

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
